application: isucfvmb-attendance
version: 2
runtime: java

static_files:
  - include: /css/**
  - include: /img/**
  - include: /js/**
  - include: /jquery/**
  - include: /MobileApp/**
  - include: /error.html
  - include: /favicon.ico
  - include: /index.html

web_xml: |
  <!-- Set XML mime-mapping so spreadsheets open properly instead of being sent as an octet/stream --> 
  <mime-mapping> 
    <extension>appcache</extension> 
    <mime-type>text/cache-manifest</mime-type> 
  </mime-mapping> 
  
sessions_enabled: true

welcome_files:
  - index.jsp

handlers:

- url: /error/*
  servlet: edu.iastate.music.marching.attendance.servlets.ErrorServlet
  init_params:
    path: "error"
  name: error

- url: /auth/*
  servlet: edu.iastate.music.marching.attendance.servlets.AuthServlet
  init_params:
    path: "auth"
  name: auth

- url: /director/*
  servlet: edu.iastate.music.marching.attendance.servlets.DirectorServlet
  init_params:
    path: "director"
  name: director

- url: /director/forms/*
  servlet: edu.iastate.music.marching.attendance.servlets.FormsServlet
  init_params:
    userType: Director
    path: "director/forms"
  name: director_forms

- url: /director/messages/*
  servlet: edu.iastate.music.marching.attendance.servlets.MessagingServlet
  init_params:
    userType: Director
    path: "director/messages"
  name: director_messages

- url: /MobileApp/data/*
  servlet: edu.iastate.music.marching.attendance.servlets.MobileAppDataServlet
  init_params:
    path: "MobileApp/data"
  name: mobileapp_data

- url: /student/*
  servlet: edu.iastate.music.marching.attendance.servlets.StudentServlet
  init_params:
    path: "student"
  name: student

- url: /student/forms/*
  servlet: edu.iastate.music.marching.attendance.servlets.FormsServlet
  init_params:
    userType: Student
    path: "student/forms"
  name: student_forms

- url: /student/messages/*
  servlet: edu.iastate.music.marching.attendance.servlets.MessagingServlet
  init_params:
    userType: Student
    path: "student/messages"
  name: student_messages

- url: /ta/*
  servlet: edu.iastate.music.marching.attendance.servlets.TAServlet
  init_params:
    path: "ta"
  name: ta

- url: /admin/*
  servlet: edu.iastate.music.marching.attendance.servlets.AdminServlet
  secure: always
  login: admin
  init_params:
    path: "admin"
  name: admin

error_handlers:
  - file: /error.html
