application: isucfvmb-attendance
version: 2
runtime: java

static_files:
  - include: /css/**
  - include: /img/**
  - include: /js/**
  - include: /MobileApp/**
  - include: /error.html
  - include: /favicon.ico
  - include: /index.html
  
sessions_enabled: true

welcome_files:
  - homepage

handlers:
  
- url: /homepage
  servlet: edu.iastate.music.marching.attendance.servlets.HomepageServlet
  
- url: /error
  servlet: edu.iastate.music.marching.attendance.servlets.ErrorServlet

- url: /auth/*
  servlet: edu.iastate.music.marching.attendance.servlets.AuthServlet

- url: /director/*
  servlet: edu.iastate.music.marching.attendance.servlets.DirectorServlet

- url: /forms/*
  servlet: edu.iastate.music.marching.attendance.servlets.FormsServlet

- url: /MobileApp/data/*
  servlet: edu.iastate.music.marching.attendance.servlets.MobileAppDataServlet

- url: /student/*
  servlet: edu.iastate.music.marching.attendance.servlets.StudentServlet

- url: /student/forms/*
  servlet: edu.iastate.music.marching.attendance.servlets.FormsServlet

- url: /ta/*
  servlet: edu.iastate.music.marching.attendance.servlets.TAServlet


error_handlers:
  - file: /error.html
