application: isucfvmb-attendance
version: 2
runtime: java

public_root: /public

static_files:
  - include: /public/**
  - include: /MobileApp/**
  

welcome_files:
  - index.jsp
  - index.html
  
sessions_enabled: true


handlers:

- url: /auth/*
  servlet: edu.iastate.music.marching.attendance.servlets.AuthServlet

- url: /director/*
  servlet: edu.iastate.music.marching.attendance.servlets.DirectorServlet

- url: /forms/*
  servlet: edu.iastate.music.marching.attendance.servlets.FormsServlet

- url: /MobileApp/data/*
  servlet: edu.iastate.music.marching.attendance.servlets.MobileAppDataServlet

- url: /student/*
  servlet: edu.iastate.music.marching.attendance.servlets.StudentServlet
  
- url: /ta/*
  servlet: edu.iastate.music.marching.attendance.servlets.TAServlet




error_handlers:
  - file: /error.html
  
web_xml: |
  <error-page>
    <error-code>404</error-code>
    <location>/error.html</location>
  </error-page>
  <error-page>
    <error-code>405</error-code>
    <location>/error.html</location>
  </error-page>